name: push

on:
  - push

jobs:
  push:
    name: push
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'
      
      - name: install packages
        run: dotnet restore

      - name: build
        run: dotnet build --no-restore

      - name: start rabbitMQ
        uses: getong/rabbitmq-action@v1.2
        with:
          rabbitmq version: '3.10.8'
          host port: 5672
          rabbitmq user: 'guest'
          rabbitmq password: 'guest'
          rabbitmq vhost: '/'

      - name: test
        run: dotnet test --no-restore --verbosity normal