name: release

on:
  release:
    types: [published]
    branches:
      - master
    
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'
      
      - name: install packages
        run: dotnet restore

      - name: build
        run: dotnet build --no-restore

      - name: publish Byndyusoft.Messaging.RabbitMq.Abstractions
        uses: alirezanet/publish-nuget@v3.1.0
        with:
          PROJECT_FILE_PATH: src/Byndyusoft.Messaging.RabbitMq.Abstractions/Byndyusoft.Messaging.RabbitMq.Abstractions.csproj
          VERSION_FILE_PATH: Directory.Build.props
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          INCLUDE_SYMBOLS: true

      - name: publish Byndyusoft.Messaging.RabbitMq.Annotations
        uses: alirezanet/publish-nuget@v3.1.0
        with:
          PROJECT_FILE_PATH: src/Byndyusoft.Messaging.RabbitMq.Annotations/Byndyusoft.Messaging.RabbitMq.Annotations.csproj
          VERSION_FILE_PATH: Directory.Build.props
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          INCLUDE_SYMBOLS: true

      - name: publish Byndyusoft.Messaging.RabbitMq.Core
        uses: alirezanet/publish-nuget@v3.1.0
        with:
          PROJECT_FILE_PATH: src/Byndyusoft.Messaging.RabbitMq.Core/Byndyusoft.Messaging.RabbitMq.Core.csproj
          VERSION_FILE_PATH: Directory.Build.props
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          INCLUDE_SYMBOLS: true

      - name: publish Byndyusoft.Messaging.RabbitMq
        uses: alirezanet/publish-nuget@v3.1.0
        with:
          PROJECT_FILE_PATH: src/Byndyusoft.Messaging.RabbitMq/Byndyusoft.Messaging.RabbitMq.csproj
          VERSION_FILE_PATH: Directory.Build.props
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          INCLUDE_SYMBOLS: true

      - name: publish Byndyusoft.Messaging.RabbitMq.OpenTelemetry
        uses: alirezanet/publish-nuget@v3.1.0
        with:
          PROJECT_FILE_PATH: src/Byndyusoft.Messaging.RabbitMq.OpenTelemetry/Byndyusoft.Messaging.RabbitMq.OpenTelemetry.csproj
          VERSION_FILE_PATH: Directory.Build.props
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          INCLUDE_SYMBOLS: true

      - name: publish Byndyusoft.Messaging.RabbitMq.Rpc.Server
        uses: alirezanet/publish-nuget@v3.1.0
        with:
          PROJECT_FILE_PATH: src/Byndyusoft.Messaging.RabbitMq.Rpc.Server/Byndyusoft.Messaging.RabbitMq.Rpc.Server.csproj
          VERSION_FILE_PATH: Directory.Build.props
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          INCLUDE_SYMBOLS: true